// This file was automatically generated by Java-GI. Do not edit this file
// directly! Visit <https://github.com/jwharm/java-gi/> for more information.
//
// The API documentation in this file was derived from GObject-Introspection
// metadata and may include text or comments from the original C sources.
//
// Copyright (c), upstream authors as identified in the GObject-Introspection
// metadata.
//
// This generated file is distributed under the same license as the original
// GObject-Introspection data, unless otherwise specified. Users of this file
// are responsible for complying with any licenses or terms required by the
// original authors.
//
// THIS FILE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
//
package org.gnome.gtk4layershell;

import io.github.jwharm.javagi.base.Enumeration;
import java.lang.IllegalStateException;
import java.lang.Override;
import javax.annotation.processing.Generated;

@Generated("io.github.jwharm.JavaGI")
public enum KeyboardMode implements Enumeration {
    /**
     * This window should not receive keyboard events.
     */
    NONE(0),

    /**
     * This window should have exclusive focus if it is on the top or overlay layer.
     */
    EXCLUSIVE(1),

    /**
     * The user should be able to focus and unfocues this window in an implementation
     * defined way. Not supported for protocol version &lt; 4.
     */
    ON_DEMAND(2),

    /**
     * Should not be used except to get the number of entries. (NOTE: may change in
     * future releases as more entries are added)
     */
    ENTRY_NUMBER(3);

    static {
        Gtk4LayerShell.javagi$ensureInitialized();
    }

    private final int value;

    /**
     * Create a new KeyboardMode for the provided value
     *
     * @param value the enum value
     */
    private KeyboardMode(int value) {
        this.value = value;
    }

    /**
     * Create a new KeyboardMode for the provided value
     *
     * @param value the enum value
     * @return the enum for the provided value
     */
    public static KeyboardMode of(int value) {
        return switch(value) {
            case 0 -> NONE;
            case 1 -> EXCLUSIVE;
            case 2 -> ON_DEMAND;
            case 3 -> ENTRY_NUMBER;
            default -> throw new IllegalStateException("Unexpected value: " + value);
        } ;
    }

    /**
     * Get the numeric value of this enum
     *
     * @return the enum value
     */
    @Override
    public int getValue() {
        return value;
    }
}
