// This file was automatically generated by Java-GI. Do not edit this file
// directly! Visit <https://java-gi.org> for more information.
//
// The API documentation in this file was derived from GObject-Introspection
// metadata and may include text or comments from the original C sources.
//
// Copyright (c), upstream authors of the GObject-Introspection data.
//
// This generated file is distributed under the same license as the original
// GObject-Introspection data, unless otherwise specified. Users of this file
// are responsible for complying with any licenses or terms required by the
// original authors.
//
// THIS FILE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT.
//
package org.gnome.gtk4layershell;

import java.lang.IllegalStateException;
import java.lang.Override;
import java.lang.foreign.MemorySegment;
import javax.annotation.processing.Generated;
import org.javagi.base.Enumeration;

@Generated("org.javagi.JavaGI")
public enum Layer implements Enumeration {
    ///
    /// The background layer.
    ///
    BACKGROUND(0),

    ///
    /// The bottom layer.
    ///
    BOTTOM(1),

    ///
    /// The top layer.
    ///
    TOP(2),

    ///
    /// The overlay layer.
    ///
    OVERLAY(3),

    ///
    /// Should not be used except to get the number of entries. (NOTE: may change in
    /// future releases as more entries are added)
    ///
    ENTRY_NUMBER(4);

    static {
        Gtk4LayerShell.javagi$ensureInitialized();
    }

    private final int value;

    ///
    /// Create a new Layer for the provided value
    ///
    /// @param value the enum value
    ///
    private Layer(int value) {
        this.value = value;
    }

    ///
    /// Create a new Layer for the provided value
    ///
    /// @param value the enum value
    /// @return the enum for the provided value
    ///
    public static Layer of(int value) {
        return switch(value) {
            case 0 -> BACKGROUND;
            case 1 -> BOTTOM;
            case 2 -> TOP;
            case 3 -> OVERLAY;
            case 4 -> ENTRY_NUMBER;
            default -> throw new IllegalStateException("Unexpected value: " + value);
        } ;
    }

    ///
    /// Get the numeric value of this enum
    ///
    /// @return the enum value
    ///
    @Override
    public int getValue() {
        return value;
    }

    ///
    /// Create a new Layer for the value in the provided memory address.
    ///
    /// @param address the memory address holding a enum value
    /// @return the enum for the value in the provided memory address
    ///
    public static Layer of(MemorySegment address) {
        return of((int) address.address());
    }
}
